# Site settings
title: Bruna Pinos
description: "Software Engineering student | GSoC 2019 Student Developer of TensorFlow | Chatbot developer | Interested in free/libre/open source software (FLOSS)"
url: 'http://brunapinos.com/'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Bruna Pinos'
  email: brunapinos@gmail.com
  twitter_username: brunapinos
  facebook_username: brunapinos
  github_username:  brunapinos
  linkedin_username:  brunapinos

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
